POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer <Your token>

{"query":"mutation {addShow(title:\"batman\", releaseYear:2019) {id,title,releaseYear}}"}

############

POST http://localhost:8080/graphql
Content-Type: application/json

{"query":"mutation {addShow(title:\"Top Gun\", releaseYear:2019) {id,title,releaseYear}}"}

############

POST http://localhost:8080/graphql
Content-Type: application/graphql
Authorization: Bearer <Your token>

{
  shows {
     title
     releaseYear
  }
}

#######################

POST http://localhost:8080/graphql
Content-Type: application/graphql

{
  shows(titleFilter: "Top Gun") {
        id,
        title,
        releaseYear
    }
}